language: python

matrix:
  include:
  - dist: xenial
    os: linux
    language: python
    python: "3.5"
  - dist: xenial
    os: linux
    language: python
    python: "3.6"
  - dist: trusty
    os: linux
    language: python
    python: "3.5"
  - dist: trusty
    os: linux
    language: python
    python: "3.6"
    
install:
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install pandas
  - pip install -r requirements.txt
  - pip install .
  - pip install 'pytest>=3.6'
  - pip install pytest-cov coverage coveralls

script:
  - pytest --cov seglearn
  - python examples/plot_regression.py
  - python examples/plot_forecast.py

after_success:
  - coveralls 
