language: python

os:
  - linux
  
jobs:
  include:
  - dist: trusty
  - dist: bionic

python:
  - "3.5"
  - "3.6"
  - "3.8"

install:
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install pandas
  - pip install -r requirements.txt
  - pip install .
  - pip install 'pytest>=3.6'
  - pip install pytest-cov coverage coveralls

script:
  - pytest --cov seglearn
  - python examples/plot_regression.py
  - python examples/plot_forecast.py

after_success:
  - coveralls 
